### ISSUE TITLE
docs: proper screenshot

### ISSUE THREAD

**Issue by jef** [jef/everforest-xresources#1]
### Problem

Need a screenshot of this theme in use.

### Expected output

A relevant screenshot.

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/111672493-06e6b700-8840-11eb-8c5f-94102045dd0e.png)

![image](https://user-images.githubusercontent.com/59060246/111671285-cdfa1280-883e-11eb-91c3-0c8f686880ef.png)

**Comment by siduck** [comment]
@jef Here are some :)

**Comment by jef** [comment]
Thank you!!!
